"use client"

import { createContext, useContext, useEffect, useState } from "react"
import { createClient } from "@/lib/supabase/client"

type Language = "en" | "tr"

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.tasks": "Tasks",
    "nav.aims": "Aims",
    "nav.games": "Games",
    "nav.media": "Media Hub",
    "nav.journal": "Journal",
    "nav.friends": "Friends",
    "nav.chat": "Chat",
    "nav.blueprints": "Blueprints",
    "nav.achievements": "Achievements",
    "nav.settings": "Settings",
    "nav.signOut": "Sign Out",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.description": "Your personal hub overview",
    "dashboard.activeAims": "Active Aims",
    "dashboard.gamesPlaying": "Games Playing",
    "dashboard.tasksCompleted": "Tasks Completed",
    "dashboard.achievements": "Achievements",
    "dashboard.badgesUnlocked": "badges unlocked",
    "dashboard.aimsProgress": "Aims Progress",
    "dashboard.averageProgress": "Average progress across all active aims",
    "dashboard.overallProgress": "Overall Progress",
    "dashboard.activeAimsCount": "You have {count} active aim(s) in progress",
    "dashboard.noAims": "Start by creating your first aim",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.quickActionsDesc": "Get started with common tasks",
    "dashboard.newAim": "New Aim",
    "dashboard.addGame": "Add Game",
    "dashboard.writeEntry": "Write Entry",
    "dashboard.addTask": "Add Task",
    
    // Aims
    "aims.title": "Aims",
    "aims.description": "Track and manage your goals",
    "aims.search": "Search aims...",
    "aims.all": "All",
    "aims.active": "Active",
    "aims.completed": "Completed",
    "aims.paused": "Paused",
    "aims.archived": "Archived",
    "aims.noFound": "No aims found",
    "aims.noFoundDesc": "Try a different search term",
    "aims.noAims": "Add your first aim to get started",
    "aims.progress": "Progress",
    "aims.due": "Due",
    "aims.addNew": "Add New Aim",
    "aims.addNewDesc": "Create a new goal to track your progress",
    "aims.title_field": "Title",
    "aims.titlePlaceholder": "Your aim",
    "aims.description_field": "Description",
    "aims.descriptionPlaceholder": "Optional description",
    "aims.priority": "Priority",
    "aims.priority.low": "Low",
    "aims.priority.medium": "Medium",
    "aims.priority.high": "High",
    "aims.priority.urgent": "Urgent",
    "aims.dueDate": "Due Date",
    "aims.color": "Color",
    "aims.status": "Status",
    "aims.status.active": "Active",
    "aims.status.completed": "Completed",
    "aims.status.paused": "Paused",
    "aims.status.archived": "Archived",
    "aims.create": "Create Aim",
    "aims.update": "Update Aim",
    "aims.created": "Aim created",
    "aims.updated": "Aim updated",
    "aims.deleted": "Aim deleted",
    "aims.createError": "Failed to create aim",
    "aims.updateError": "Failed to update aim",
    "aims.deleteError": "Failed to delete aim",
    
    // Games
    "games.title": "Games",
    "games.description": "Track your gaming progress",
    "games.search": "Search games...",
    "games.all": "All",
    "games.playing": "Playing",
    "games.completed": "Completed",
    "games.backlog": "Backlog",
    "games.paused": "Paused",
    "games.dropped": "Dropped",
    "games.noFound": "No games found",
    "games.noGames": "Add your first game to get started",
    "games.tasks": "Tasks",
    "games.addNew": "Add New Game",
    "games.addNewDesc": "Add a game to your library to track your progress",
    "games.titlePlaceholder": "Game title",
    "games.status": "Status",
    "games.platform": "Platform",
    "games.platformPlaceholder": "e.g., PC, PS5",
    "games.hoursPlayed": "Hours Played",
    "games.rating": "Rating (0-10)",
    "games.coverImage": "Cover Image URL",
    "games.startedDate": "Started Date",
    "games.completedDate": "Completed Date",
    "games.add": "Add Game",
    "games.created": "Game added successfully",
    "games.updated": "Game updated successfully",
    "games.deleted": "Game deleted",
    "games.createError": "Failed to add game",
    "games.updateError": "Failed to update game",
    "games.deleteError": "Failed to delete game",
    
    // Tasks
    "tasks.title": "Task Manager",
    "tasks.description": "Manage all your tasks in one place",
    "tasks.search": "Search tasks...",
    "tasks.allPriorities": "All Priorities",
    "tasks.all": "All",
    "tasks.general": "General",
    "tasks.aims": "Aims",
    "tasks.games": "Games",
    "tasks.daily": "Daily",
    "tasks.todo": "To Do",
    "tasks.completed": "Completed",
    "tasks.noFound": "No tasks found",
    "tasks.addNew": "Add New Task",
    "tasks.addNewDesc": "Create a new task to track your progress",
    "tasks.titlePlaceholder": "Task title",
    "tasks.category": "Category",
    "tasks.category.general": "General",
    "tasks.category.aim": "Aim",
    "tasks.category.game": "Game",
    "tasks.category.daily": "Daily",
    "tasks.linkToAim": "Link to Aim",
    "tasks.linkToGame": "Link to Game",
    "tasks.selectAim": "Select an aim",
    "tasks.selectGame": "Select a game",
    "tasks.dueDate": "Due Date",
    "tasks.dueTime": "Due Time",
    "tasks.priority": "Priority",
    "tasks.status": "Status",
    "tasks.status.pending": "Pending",
    "tasks.status.inProgress": "In Progress",
    "tasks.status.completed": "Completed",
    "tasks.status.cancelled": "Cancelled",
    "tasks.create": "Create Task",
    "tasks.update": "Update Task",
    "tasks.edit": "Edit Task",
    "tasks.editDesc": "Update your task details",
    "tasks.created": "Task created",
    "tasks.updated": "Task updated",
    "tasks.deleted": "Task deleted",
    "tasks.createError": "Failed to create task",
    "tasks.updateError": "Failed to update task",
    "tasks.deleteError": "Failed to delete task",
    
    // Journal
    "journal.title": "Daily Journal",
    "journal.description": "Document your thoughts and experiences",
    "journal.newEntry": "New Entry",
    "journal.recentEntries": "Recent Entries",
    "journal.noEntries": "No journal entries yet",
    "journal.noEntriesDesc": "Click on a date to start writing",
    "journal.days.sun": "Sun",
    "journal.days.mon": "Mon",
    "journal.days.tue": "Tue",
    "journal.days.wed": "Wed",
    "journal.days.thu": "Thu",
    "journal.days.fri": "Fri",
    "journal.days.sat": "Sat",
    "journal.mood": "How are you feeling?",
    "journal.mood.great": "Great",
    "journal.mood.good": "Good",
    "journal.mood.okay": "Okay",
    "journal.mood.bad": "Bad",
    "journal.mood.terrible": "Terrible",
    "journal.titleOptional": "Title (optional)",
    "journal.titlePlaceholder": "Give your entry a title...",
    "journal.content": "Content",
    "journal.contentPlaceholder": "Write about your day...",
    "journal.linkToAim": "Link to Aim (optional)",
    "journal.linkToGame": "Link to Game (optional)",
    "journal.created": "Entry created",
    "journal.updated": "Entry updated",
    "journal.deleted": "Entry deleted",
    "journal.createError": "Failed to save entry",
    "journal.updateError": "Failed to update entry",
    "journal.deleteError": "Failed to delete entry",
    
    // Media
    "media.title": "Media Hub",
    "media.description": "Manage your learning resources",
    "media.search": "Search resources...",
    "media.all": "All",
    "media.videos": "Videos",
    "media.articles": "Articles",
    "media.other": "Other",
    "media.noFound": "No resources found",
    "media.noResources": "Add your first resource to get started",
    "media.view": "View",
    "media.markWatched": "Mark as Watched",
    "media.markUnwatched": "Mark as Unwatched",
    "media.openOriginal": "Open Original",
    "media.addNew": "Add New Resource",
    "media.addNewDesc": "Save a video, article, or document to your media hub",
    "media.url": "URL",
    "media.urlPlaceholder": "https://youtube.com/watch?v=...",
    "media.titlePlaceholder": "Resource title",
    "media.type": "Type",
    "media.type.youtube": "YouTube Video",
    "media.type.article": "Article",
    "media.type.document": "Document",
    "media.type.other": "Other",
    "media.add": "Add Resource",
    "media.created": "Resource added successfully",
    "media.updated": "Resource updated successfully",
    "media.deleted": "Resource deleted",
    "media.createError": "Failed to add resource",
    "media.updateError": "Failed to update resource",
    "media.deleteError": "Failed to delete resource",
    
    // Friends
    "friends.title": "Friends",
    "friends.description": "Connect with other users",
    "friends.search": "Search friends...",
    "friends.findUsers": "Find Users",
    "friends.friends": "Friends",
    "friends.requests": "Requests",
    "friends.sent": "Sent",
    "friends.noFriends": "No friends yet",
    "friends.noFriendsDesc": "Find users and send friend requests to connect",
    "friends.noRequests": "No pending requests",
    "friends.noRequestsDesc": "Friend requests you receive will appear here",
    "friends.noSent": "No sent requests",
    "friends.noSentDesc": "Requests you send will appear here",
    "friends.sendMessage": "Send Message",
    "friends.removeFriend": "Remove Friend",
    "friends.blockUser": "Block User",
    "friends.message": "Message",
    "friends.findUsersTitle": "Find Users",
    "friends.findUsersDesc": "Search for other NathanIs users by name or handle",
    "friends.searchPlaceholder": "Search by name or @handle...",
    "friends.noUsersFound": "No users found matching",
    "friends.pending": "Pending",
    "friends.add": "Add",
    
    // Blueprints
    "blueprints.title": "Blueprints",
    "blueprints.description": "Reusable routine templates",
    "blueprints.search": "Search blueprints...",
    "blueprints.create": "Create Blueprint",
    "blueprints.discover": "Discover",
    "blueprints.myBlueprints": "My Blueprints",
    "blueprints.noFound": "No blueprints found",
    "blueprints.noFoundDesc": "Be the first to share a blueprint!",
    "blueprints.noBlueprints": "No blueprints yet",
    "blueprints.noBlueprintsDesc": "Create your first blueprint to share your routines",
    "blueprints.createTitle": "Create Blueprint",
    "blueprints.createDesc": "Create a reusable routine template that others can clone",
    "blueprints.titlePlaceholder": "My Study Routine",
    "blueprints.descriptionPlaceholder": "Describe your blueprint...",
    "blueprints.category": "Category",
    "blueprints.category.study": "Study",
    "blueprints.category.fitness": "Fitness",
    "blueprints.category.productivity": "Productivity",
    "blueprints.category.gaming": "Gaming",
    "blueprints.category.lifestyle": "Lifestyle",
    "blueprints.category.general": "General",
    "blueprints.makePublic": "Make Public",
    "blueprints.makePublicDesc": "Public blueprints can be discovered by others",
    "blueprints.tasks": "Tasks",
    "blueprints.addTask": "Add Task",
    "blueprints.taskTitle": "Task title",
    "blueprints.taskDescription": "Description (optional)",
    "blueprints.createBlueprint": "Create Blueprint",
    "blueprints.created": "Blueprint created!",
    "blueprints.createdPublic": "It will be visible after approval",
    "blueprints.createdPrivate": "Saved to your blueprints",
    "blueprints.createError": "Failed to create blueprint",
    "blueprints.tasksCount": "{count} tasks",
    "blueprints.clonesCount": "{count} clones",
    "blueprints.clone": "Clone",
    "blueprints.cloned": "Blueprint cloned!",
    "blueprints.clonedDesc": "{count} tasks added to your list",
    "blueprints.cloneError": "Failed to clone blueprint",
    
    // Achievements
    "achievements.title": "Achievements",
    "achievements.description": "Your unlocked badges and rewards",
    "achievements.xpReward": "+{xp} XP",
    "achievements.locked": "Locked",
    "achievements.unlocked": "Unlocked",
    
    // Settings
    "settings.title": "Settings",
    "settings.description": "Manage your account and preferences",
    "settings.profile": "Profile",
    "settings.notifications": "Notifications",
    "settings.account": "Account",
    "settings.profileInfo": "Profile Information",
    "settings.profileInfoDesc": "Update your personal information and avatar",
    "settings.avatarUrl": "Avatar URL",
    "settings.avatarPlaceholder": "https://...",
    "settings.avatarDesc": "Enter a URL to your profile picture (MAL-style)",
    "settings.displayName": "Display Name",
    "settings.displayNamePlaceholder": "Your name",
    "settings.handle": "Handle",
    "settings.handlePlaceholder": "yourhandle",
    "settings.handleDesc": "This is your unique NathanIs handle for discovery",
    "settings.bio": "Bio",
    "settings.bioPlaceholder": "Tell us about yourself...",
    "settings.publicProfile": "Public Profile",
    "settings.publicProfileDesc": "Allow others to find and view your profile",
    "settings.public": "Public",
    "settings.private": "Private",
    "settings.defaultAvatars": "Default Avatars",
    "settings.defaultAvatarsDesc": "Choose from our collection of avatars",
    "settings.notificationSettings": "Notification Settings",
    "settings.notificationSettingsDesc": "Configure how you receive notifications from NathanIs Hub",
    "settings.enableNotifications": "Enable Notifications",
    "settings.enableNotificationsDesc": "Master toggle for all notifications",
    "settings.achievementAlerts": "Achievement Alerts",
    "settings.achievementAlertsDesc": "Get notified when you unlock badges",
    "settings.friendAlerts": "Friend Alerts",
    "settings.friendAlertsDesc": "Friend requests and social notifications",
    "settings.taskReminders": "Task Reminders",
    "settings.taskRemindersDesc": "Reminders for scheduled tasks",
    "settings.systemNotifications": "System Notifications",
    "settings.systemNotificationsDesc": "Important system updates and alerts",
    "settings.accountInfo": "Account Information",
    "settings.accountInfoDesc": "Your account details",
    "settings.email": "Email",
    "settings.language": "Language",
    "settings.languageDesc": "Choose your preferred language",
    "settings.accountId": "Account ID",
    "settings.memberSince": "Member Since",
    "settings.statistics": "Statistics",
    "settings.statisticsDesc": "Your activity summary",
    "settings.totalXp": "Total XP",
    "settings.level": "Level",
    "settings.currentStreak": "Current Streak",
    "settings.tasksCompleted": "Tasks Completed",
    "settings.journalEntries": "Journal Entries",
    "settings.save": "Save Changes",
    "settings.saveSettings": "Save Settings",
    "settings.success": "Settings updated successfully",
    "settings.error": "Failed to update settings",
    "settings.notificationSuccess": "Notification settings saved",
    "settings.notificationError": "Failed to save settings",
    
    // Gamification
    "gamification.level": "Level {level}",
    "gamification.totalXp": "Total XP",
    "gamification.progressToLevel": "Progress to Level {level}",
    "gamification.xpToNext": "{xp} XP to next level",
    "gamification.xpTotal": "{xp} XP total",
    "gamification.dayStreak": "day streak",
    "gamification.bestStreak": "Best: {days} days",
    "gamification.levelUp": "Level Up!",
    "gamification.achievementUnlocked": "Achievement Unlocked!",
    
    // Common
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.update": "Update",
    "common.add": "Add",
    "common.remove": "Remove",
    "common.close": "Close",
    "common.open": "Open",
    "common.view": "View",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.yes": "Yes",
    "common.no": "No",
    "common.ok": "OK",
    "common.confirm": "Confirm",
    "common.success": "Success",
    "common.error": "Error",
    "common.warning": "Warning",
    "common.info": "Info",
    "common.required": "Required",
    "common.optional": "Optional",
    "common.none": "None",
    "common.all": "All",
    "common.today": "Today",
    "common.yesterday": "Yesterday",
    "common.tomorrow": "Tomorrow",
    "common.days": "days",
  },
  tr: {
    // Navigation
    "nav.dashboard": "Ana Sayfa",
    "nav.tasks": "Görevler",
    "nav.aims": "Hedefler",
    "nav.games": "Oyunlar",
    "nav.media": "Medya Merkezi",
    "nav.journal": "Günlük",
    "nav.friends": "Arkadaşlar",
    "nav.chat": "Sohbet",
    "nav.blueprints": "Şablonlar",
    "nav.achievements": "Başarımlar",
    "nav.settings": "Ayarlar",
    "nav.signOut": "Çıkış Yap",
    
    // Dashboard
    "dashboard.title": "Ana Sayfa",
    "dashboard.description": "Kişisel hub'ınıza genel bakış",
    "dashboard.activeAims": "Aktif Hedefler",
    "dashboard.gamesPlaying": "Oynanan Oyunlar",
    "dashboard.tasksCompleted": "Tamamlanan Görevler",
    "dashboard.achievements": "Başarımlar",
    "dashboard.badgesUnlocked": "rozet kazanıldı",
    "dashboard.aimsProgress": "Hedef İlerlemesi",
    "dashboard.averageProgress": "Tüm aktif hedeflerin ortalama ilerlemesi",
    "dashboard.overallProgress": "Genel İlerleme",
    "dashboard.activeAimsCount": "{count} aktif hedefiniz devam ediyor",
    "dashboard.noAims": "İlk hedefinizi oluşturarak başlayın",
    "dashboard.quickActions": "Hızlı İşlemler",
    "dashboard.quickActionsDesc": "Yaygın görevlerle başlayın",
    "dashboard.newAim": "Yeni Hedef",
    "dashboard.addGame": "Oyun Ekle",
    "dashboard.writeEntry": "Günlük Yaz",
    "dashboard.addTask": "Görev Ekle",
    
    // Aims
    "aims.title": "Hedefler",
    "aims.description": "Hedeflerinizi takip edin ve yönetin",
    "aims.search": "Hedef ara...",
    "aims.all": "Tümü",
    "aims.active": "Aktif",
    "aims.completed": "Tamamlandı",
    "aims.paused": "Duraklatıldı",
    "aims.archived": "Arşivlendi",
    "aims.noFound": "Hedef bulunamadı",
    "aims.noFoundDesc": "Farklı bir arama terimi deneyin",
    "aims.noAims": "İlk hedefinizi ekleyerek başlayın",
    "aims.progress": "İlerleme",
    "aims.due": "Bitiş",
    "aims.addNew": "Yeni Hedef Ekle",
    "aims.addNewDesc": "İlerlemesini takip etmek için yeni bir hedef oluşturun",
    "aims.title_field": "Başlık",
    "aims.titlePlaceholder": "Hedefiniz",
    "aims.description_field": "Açıklama",
    "aims.descriptionPlaceholder": "İsteğe bağlı açıklama",
    "aims.priority": "Öncelik",
    "aims.priority.low": "Düşük",
    "aims.priority.medium": "Orta",
    "aims.priority.high": "Yüksek",
    "aims.priority.urgent": "Acil",
    "aims.dueDate": "Bitiş Tarihi",
    "aims.color": "Renk",
    "aims.status": "Durum",
    "aims.status.active": "Aktif",
    "aims.status.completed": "Tamamlandı",
    "aims.status.paused": "Duraklatıldı",
    "aims.status.archived": "Arşivlendi",
    "aims.create": "Hedef Oluştur",
    "aims.update": "Hedef Güncelle",
    "aims.created": "Hedef oluşturuldu",
    "aims.updated": "Hedef güncellendi",
    "aims.deleted": "Hedef silindi",
    "aims.createError": "Hedef oluşturulamadı",
    "aims.updateError": "Hedef güncellenemedi",
    "aims.deleteError": "Hedef silinemedi",
    
    // Games
    "games.title": "Oyunlar",
    "games.description": "Oyun ilerlemenizi takip edin",
    "games.search": "Oyun ara...",
    "games.all": "Tümü",
    "games.playing": "Oynuyor",
    "games.completed": "Tamamlandı",
    "games.backlog": "Beklemede",
    "games.paused": "Duraklatıldı",
    "games.dropped": "Bırakıldı",
    "games.noFound": "Oyun bulunamadı",
    "games.noGames": "İlk oyununuzu ekleyerek başlayın",
    "games.tasks": "Görevler",
    "games.addNew": "Yeni Oyun Ekle",
    "games.addNewDesc": "İlerlemesini takip etmek için kütüphanenize oyun ekleyin",
    "games.titlePlaceholder": "Oyun adı",
    "games.status": "Durum",
    "games.platform": "Platform",
    "games.platformPlaceholder": "örn. PC, PS5",
    "games.hoursPlayed": "Oynanan Saat",
    "games.rating": "Değerlendirme (0-10)",
    "games.coverImage": "Kapak Resmi URL",
    "games.startedDate": "Başlama Tarihi",
    "games.completedDate": "Tamamlama Tarihi",
    "games.add": "Oyun Ekle",
    "games.created": "Oyun başarıyla eklendi",
    "games.updated": "Oyun başarıyla güncellendi",
    "games.deleted": "Oyun silindi",
    "games.createError": "Oyun eklenemedi",
    "games.updateError": "Oyun güncellenemedi",
    "games.deleteError": "Oyun silinemedi",
    
    // Tasks
    "tasks.title": "Görev Yöneticisi",
    "tasks.description": "Tüm görevlerinizi tek yerde yönetin",
    "tasks.search": "Görev ara...",
    "tasks.allPriorities": "Tüm Öncelikler",
    "tasks.all": "Tümü",
    "tasks.general": "Genel",
    "tasks.aims": "Hedefler",
    "tasks.games": "Oyunlar",
    "tasks.daily": "Günlük",
    "tasks.todo": "Yapılacak",
    "tasks.completed": "Tamamlandı",
    "tasks.noFound": "Görev bulunamadı",
    "tasks.addNew": "Yeni Görev Ekle",
    "tasks.addNewDesc": "İlerlemesini takip etmek için yeni bir görev oluşturun",
    "tasks.titlePlaceholder": "Görev başlığı",
    "tasks.category": "Kategori",
    "tasks.category.general": "Genel",
    "tasks.category.aim": "Hedef",
    "tasks.category.game": "Oyun",
    "tasks.category.daily": "Günlük",
    "tasks.linkToAim": "Hedefe Bağla",
    "tasks.linkToGame": "Oyuna Bağla",
    "tasks.selectAim": "Bir hedef seçin",
    "tasks.selectGame": "Bir oyun seçin",
    "tasks.dueDate": "Bitiş Tarihi",
    "tasks.dueTime": "Bitiş Saati",
    "tasks.priority": "Öncelik",
    "tasks.status": "Durum",
    "tasks.status.pending": "Beklemede",
    "tasks.status.inProgress": "Devam Ediyor",
    "tasks.status.completed": "Tamamlandı",
    "tasks.status.cancelled": "İptal Edildi",
    "tasks.create": "Görev Oluştur",
    "tasks.update": "Görev Güncelle",
    "tasks.edit": "Görev Düzenle",
    "tasks.editDesc": "Görev detaylarınızı güncelleyin",
    "tasks.created": "Görev oluşturuldu",
    "tasks.updated": "Görev güncellendi",
    "tasks.deleted": "Görev silindi",
    "tasks.createError": "Görev oluşturulamadı",
    "tasks.updateError": "Görev güncellenemedi",
    "tasks.deleteError": "Görev silinemedi",
    
    // Journal
    "journal.title": "Günlük",
    "journal.description": "Düşüncelerinizi ve deneyimlerinizi kaydedin",
    "journal.newEntry": "Yeni Giriş",
    "journal.recentEntries": "Son Girişler",
    "journal.noEntries": "Henüz günlük girişi yok",
    "journal.noEntriesDesc": "Yazmaya başlamak için bir tarihe tıklayın",
    "journal.days.sun": "Paz",
    "journal.days.mon": "Pzt",
    "journal.days.tue": "Sal",
    "journal.days.wed": "Çar",
    "journal.days.thu": "Per",
    "journal.days.fri": "Cum",
    "journal.days.sat": "Cmt",
    "journal.mood": "Nasıl hissediyorsunuz?",
    "journal.mood.great": "Harika",
    "journal.mood.good": "İyi",
    "journal.mood.okay": "Fena Değil",
    "journal.mood.bad": "Kötü",
    "journal.mood.terrible": "Berbat",
    "journal.titleOptional": "Başlık (isteğe bağlı)",
    "journal.titlePlaceholder": "Girişinize bir başlık verin...",
    "journal.content": "İçerik",
    "journal.contentPlaceholder": "Gününüz hakkında yazın...",
    "journal.linkToAim": "Hedefe Bağla (isteğe bağlı)",
    "journal.linkToGame": "Oyuna Bağla (isteğe bağlı)",
    "journal.created": "Giriş oluşturuldu",
    "journal.updated": "Giriş güncellendi",
    "journal.deleted": "Giriş silindi",
    "journal.createError": "Giriş kaydedilemedi",
    "journal.updateError": "Giriş güncellenemedi",
    "journal.deleteError": "Giriş silinemedi",
    
    // Media
    "media.title": "Medya Merkezi",
    "media.description": "Öğrenme kaynaklarınızı yönetin",
    "media.search": "Kaynak ara...",
    "media.all": "Tümü",
    "media.videos": "Videolar",
    "media.articles": "Makaleler",
    "media.other": "Diğer",
    "media.noFound": "Kaynak bulunamadı",
    "media.noResources": "İlk kaynağınızı ekleyerek başlayın",
    "media.view": "Görüntüle",
    "media.markWatched": "İzlendi Olarak İşaretle",
    "media.markUnwatched": "İzlenmedi Olarak İşaretle",
    "media.openOriginal": "Orijinali Aç",
    "media.addNew": "Yeni Kaynak Ekle",
    "media.addNewDesc": "Medya merkezinize video, makale veya belge kaydedin",
    "media.url": "URL",
    "media.urlPlaceholder": "https://youtube.com/watch?v=...",
    "media.titlePlaceholder": "Kaynak başlığı",
    "media.type": "Tür",
    "media.type.youtube": "YouTube Videosu",
    "media.type.article": "Makale",
    "media.type.document": "Belge",
    "media.type.other": "Diğer",
    "media.add": "Kaynak Ekle",
    "media.created": "Kaynak başarıyla eklendi",
    "media.updated": "Kaynak başarıyla güncellendi",
    "media.deleted": "Kaynak silindi",
    "media.createError": "Kaynak eklenemedi",
    "media.updateError": "Kaynak güncellenemedi",
    "media.deleteError": "Kaynak silinemedi",
    
    // Friends
    "friends.title": "Arkadaşlar",
    "friends.description": "Diğer kullanıcılarla bağlantı kurun",
    "friends.search": "Arkadaş ara...",
    "friends.findUsers": "Kullanıcı Bul",
    "friends.friends": "Arkadaşlar",
    "friends.requests": "İstekler",
    "friends.sent": "Gönderilen",
    "friends.noFriends": "Henüz arkadaş yok",
    "friends.noFriendsDesc": "Kullanıcı bulun ve bağlantı kurmak için arkadaşlık isteği gönderin",
    "friends.noRequests": "Bekleyen istek yok",
    "friends.noRequestsDesc": "Aldığınız arkadaşlık istekleri burada görünecek",
    "friends.noSent": "Gönderilen istek yok",
    "friends.noSentDesc": "Gönderdiğiniz istekler burada görünecek",
    "friends.sendMessage": "Mesaj Gönder",
    "friends.removeFriend": "Arkadaşlıktan Çıkar",
    "friends.blockUser": "Kullanıcıyı Engelle",
    "friends.message": "Mesaj",
    "friends.findUsersTitle": "Kullanıcı Bul",
    "friends.findUsersDesc": "İsim veya kullanıcı adıyla diğer NathanIs kullanıcılarını arayın",
    "friends.searchPlaceholder": "İsim veya @kullanıcıadı ile ara...",
    "friends.noUsersFound": "Eşleşen kullanıcı bulunamadı",
    "friends.pending": "Beklemede",
    "friends.add": "Ekle",
    
    // Blueprints
    "blueprints.title": "Şablonlar",
    "blueprints.description": "Yeniden kullanılabilir rutin şablonları",
    "blueprints.search": "Şablon ara...",
    "blueprints.create": "Şablon Oluştur",
    "blueprints.discover": "Keşfet",
    "blueprints.myBlueprints": "Şablonlarım",
    "blueprints.noFound": "Şablon bulunamadı",
    "blueprints.noFoundDesc": "İlk şablonu paylaşan siz olun!",
    "blueprints.noBlueprints": "Henüz şablon yok",
    "blueprints.noBlueprintsDesc": "Rutinlerinizi paylaşmak için ilk şablonunuzu oluşturun",
    "blueprints.createTitle": "Şablon Oluştur",
    "blueprints.createDesc": "Başkalarının klonlayabileceği yeniden kullanılabilir rutin şablonu oluşturun",
    "blueprints.titlePlaceholder": "Çalışma Rutinim",
    "blueprints.descriptionPlaceholder": "Şablonunuzu açıklayın...",
    "blueprints.category": "Kategori",
    "blueprints.category.study": "Çalışma",
    "blueprints.category.fitness": "Fitness",
    "blueprints.category.productivity": "Verimlilik",
    "blueprints.category.gaming": "Oyun",
    "blueprints.category.lifestyle": "Yaşam Tarzı",
    "blueprints.category.general": "Genel",
    "blueprints.makePublic": "Herkese Açık Yap",
    "blueprints.makePublicDesc": "Herkese açık şablonlar başkaları tarafından keşfedilebilir",
    "blueprints.tasks": "Görevler",
    "blueprints.addTask": "Görev Ekle",
    "blueprints.taskTitle": "Görev başlığı",
    "blueprints.taskDescription": "Açıklama (isteğe bağlı)",
    "blueprints.createBlueprint": "Şablon Oluştur",
    "blueprints.created": "Şablon oluşturuldu!",
    "blueprints.createdPublic": "Onaydan sonra görünür olacak",
    "blueprints.createdPrivate": "Şablonlarınıza kaydedildi",
    "blueprints.createError": "Şablon oluşturulamadı",
    "blueprints.tasksCount": "{count} görev",
    "blueprints.clonesCount": "{count} klon",
    "blueprints.clone": "Klonla",
    "blueprints.cloned": "Şablon klonlandı!",
    "blueprints.clonedDesc": "{count} görev listenize eklendi",
    "blueprints.cloneError": "Şablon klonlanamadı",
    
    // Achievements
    "achievements.title": "Başarımlar",
    "achievements.description": "Kazandığınız rozetler ve ödüller",
    "achievements.xpReward": "+{xp} XP",
    "achievements.locked": "Kilitli",
    "achievements.unlocked": "Kazanıldı",
    
    // Settings
    "settings.title": "Ayarlar",
    "settings.description": "Hesap ayarlarınızı ve tercihlerinizi yönetin",
    "settings.profile": "Profil",
    "settings.notifications": "Bildirimler",
    "settings.account": "Hesap",
    "settings.profileInfo": "Profil Bilgileri",
    "settings.profileInfoDesc": "Kişisel bilgilerinizi ve avatarınızı güncelleyin",
    "settings.avatarUrl": "Avatar URL",
    "settings.avatarPlaceholder": "https://...",
    "settings.avatarDesc": "Profil resminizin URL'sini girin (MAL tarzı)",
    "settings.displayName": "Görünen Ad",
    "settings.displayNamePlaceholder": "Adınız",
    "settings.handle": "Kullanıcı Adı",
    "settings.handlePlaceholder": "kullaniciadi",
    "settings.handleDesc": "Bu, keşif için benzersiz NathanIs kullanıcı adınızdır",
    "settings.bio": "Biyografi",
    "settings.bioPlaceholder": "Kendiniz hakkında bilgi verin...",
    "settings.publicProfile": "Herkese Açık Profil",
    "settings.publicProfileDesc": "Başkalarının profilinizi bulmasına ve görüntülemesine izin verin",
    "settings.public": "Herkese Açık",
    "settings.private": "Özel",
    "settings.defaultAvatars": "Varsayılan Avatarlar",
    "settings.defaultAvatarsDesc": "Koleksiyonumuzdan bir avatar seçin",
    "settings.notificationSettings": "Bildirim Ayarları",
    "settings.notificationSettingsDesc": "NathanIs Hub'dan nasıl bildirim alacağınızı yapılandırın",
    "settings.enableNotifications": "Bildirimleri Etkinleştir",
    "settings.enableNotificationsDesc": "Tüm bildirimler için ana anahtar",
    "settings.achievementAlerts": "Başarım Uyarıları",
    "settings.achievementAlertsDesc": "Rozet kazandığınızda bildirim alın",
    "settings.friendAlerts": "Arkadaş Uyarıları",
    "settings.friendAlertsDesc": "Arkadaşlık istekleri ve sosyal bildirimler",
    "settings.taskReminders": "Görev Hatırlatıcıları",
    "settings.taskRemindersDesc": "Planlanmış görevler için hatırlatıcılar",
    "settings.systemNotifications": "Sistem Bildirimleri",
    "settings.systemNotificationsDesc": "Önemli sistem güncellemeleri ve uyarılar",
    "settings.accountInfo": "Hesap Bilgileri",
    "settings.accountInfoDesc": "Hesap detaylarınız",
    "settings.email": "E-posta",
    "settings.language": "Dil",
    "settings.languageDesc": "Tercih ettiğiniz dili seçin",
    "settings.accountId": "Hesap ID",
    "settings.memberSince": "Üyelik Tarihi",
    "settings.statistics": "İstatistikler",
    "settings.statisticsDesc": "Aktivite özetiniz",
    "settings.totalXp": "Toplam XP",
    "settings.level": "Seviye",
    "settings.currentStreak": "Mevcut Seri",
    "settings.tasksCompleted": "Tamamlanan Görevler",
    "settings.journalEntries": "Günlük Girişleri",
    "settings.save": "Değişiklikleri Kaydet",
    "settings.saveSettings": "Ayarları Kaydet",
    "settings.success": "Ayarlar başarıyla güncellendi",
    "settings.error": "Ayarlar güncellenirken hata oluştu",
    "settings.notificationSuccess": "Bildirim ayarları kaydedildi",
    "settings.notificationError": "Ayarlar kaydedilemedi",
    
    // Gamification
    "gamification.level": "Seviye {level}",
    "gamification.totalXp": "Toplam XP",
    "gamification.progressToLevel": "Seviye {level}'e İlerleme",
    "gamification.xpToNext": "Sonraki seviyeye {xp} XP",
    "gamification.xpTotal": "Toplam {xp} XP",
    "gamification.dayStreak": "günlük seri",
    "gamification.bestStreak": "En İyi: {days} gün",
    "gamification.levelUp": "Seviye Atladı!",
    "gamification.achievementUnlocked": "Başarım Kazanıldı!",
    
    // Common
    "common.loading": "Yükleniyor...",
    "common.save": "Kaydet",
    "common.cancel": "İptal",
    "common.delete": "Sil",
    "common.edit": "Düzenle",
    "common.create": "Oluştur",
    "common.update": "Güncelle",
    "common.add": "Ekle",
    "common.remove": "Kaldır",
    "common.close": "Kapat",
    "common.open": "Aç",
    "common.view": "Görüntüle",
    "common.search": "Ara",
    "common.filter": "Filtrele",
    "common.sort": "Sırala",
    "common.yes": "Evet",
    "common.no": "Hayır",
    "common.ok": "Tamam",
    "common.confirm": "Onayla",
    "common.success": "Başarılı",
    "common.error": "Hata",
    "common.warning": "Uyarı",
    "common.info": "Bilgi",
    "common.required": "Gerekli",
    "common.optional": "İsteğe Bağlı",
    "common.none": "Hiçbiri",
    "common.all": "Tümü",
    "common.today": "Bugün",
    "common.yesterday": "Dün",
    "common.tomorrow": "Yarın",
    "common.days": "gün",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    const loadUserLanguage = async () => {
      try {
        const supabase = createClient()
        const { data: { user } } = await supabase.auth.getUser()
        
        if (user) {
          const { data: profile } = await supabase
            .from("profiles")
            .select("preferred_language")
            .eq("id", user.id)
            .single()
          
          if (profile?.preferred_language) {
            setLanguageState(profile.preferred_language as Language)
          }
        }
      } catch (error) {
        console.error("Error loading user language:", error)
      } finally {
        setIsLoading(false)
      }
    }

    loadUserLanguage()
  }, [])

  const setLanguage = async (newLanguage: Language) => {
    setLanguageState(newLanguage)
    
    try {
      const supabase = createClient()
      const { data: { user } } = await supabase.auth.getUser()
      
      if (user) {
        await supabase
          .from("profiles")
          .update({ preferred_language: newLanguage })
          .eq("id", user.id)
      }
    } catch (error) {
      console.error("Error updating language:", error)
    }
  }

  const t = (key: string, variables?: Record<string, string | number>): string => {
    let translation = translations[language][key as keyof typeof translations[typeof language]] || key
    
    // Handle variable interpolation
    if (variables && typeof translation === 'string') {
      Object.entries(variables).forEach(([varKey, varValue]) => {
        translation = translation.replace(new RegExp(`{${varKey}}`, 'g'), String(varValue))
      })
    }
    
    return translation
  }

  if (isLoading) {
    return <div>Loading...</div>
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}